#! /bin/bash

set -euo pipefail

cd "$(dirname "$0")"

for DIR in * ; do
    if [ -d $DIR ]; then
        echo
        echo "Domain: $DIR"
        cd $DIR
        if [ -e Makefile ]; then
            # Handle "./build_all test": don't try to run "make test" if command doesn't exist.
            if [ "$#" -eq 1 ] && [ "$@" == "test" ]; then
                make --dry-run test > /dev/null && (make test > /dev/null && echo "Tests passed." || exit 1)
            else
                make "$@"
            fi
        fi
        cd ..
    fi
done
