# Without this dummy target, the test target becomes the default target.
build:
	echo nothing to build

test:
	./create_woodworking_instance.py 1 2 3
	./temporal/create_woodworking_instance.py
	rm p*.pddl
