test:
	./graph_statistics.py 1 3 5 6 2 1  # Doesn't generate instances.
	./city-generator.py 13 1000 2 100 2 6 2012 > p07.pddl
	./two-cities-generator.py 7 1000  4 100 2 8 2012 > p11.pddl
	./three-cities-generator.py 5 1000 4 100 2 9 2012 > p15.pddl
	rm p*.pddl *.tex
